server.port=8080

spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/blockfoliox?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC}
spring.datasource.username=${DB_USERNAME:your_username}
spring.datasource.password=${DB_PASSWORD:your_password}

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=${DDL_AUTO:update}
spring.jpa.show-sql=${SHOW_SQL:false}
spring.jpa.properties.hibernate.format_sql=false

jwt.secret=${JWT_SECRET:your_jwt_secret_must_be_32_chars_min}
encryption.secret=${ENCRYPTION_SECRET:your_32_character_encryption_key!!}

etherscan.api.key=${ETHERSCAN_API_KEY:your_api_key}

allowed.origins=${ALLOWED_ORIGINS:http://localhost:3000}

logging.level.com.blockfoliox.backend.security.JwtAuthFilter=WARN
logging.level.com.blockfoliox.backend.service.EncryptionService=WARN